kind: Service
apiVersion: v1
metadata:
  name: service       # Zarvis ingress looking for name 'service' by default
spec:
  ports:
  - name: http
    port: 8080        # Zarvis ingress looking for port '8080' by default
    targetPort: 8080  # Internal application default port
  selector:
    app: pedestal-api-swagger-app
