apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedestal-api-swagger-deployment
spec:
  selector:
    matchLabels:
      app: pedestal-api-swagger-app
  replicas: 1
  template:
    metadata:
      labels:
        app: pedestal-api-swagger-app
    spec:
      containers:
      - name: pedestal-api-swagger
        image: pedestal-api-swagger-img
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
